// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package testdi

import (
	"github.com/gin-gonic/gin"
	"github.com/redis/go-redis/v9"
	"github.com/sirawong/simple-banking-api/internal/adapter/postgres"
	"github.com/sirawong/simple-banking-api/internal/config"
	handler2 "github.com/sirawong/simple-banking-api/internal/handler"
	"github.com/sirawong/simple-banking-api/internal/handler/handler"
	"github.com/sirawong/simple-banking-api/internal/repository/cache"
	"github.com/sirawong/simple-banking-api/internal/repository/db"
	"github.com/sirawong/simple-banking-api/internal/service/account"
	"github.com/sirawong/simple-banking-api/internal/service/auth"
	"github.com/sirawong/simple-banking-api/internal/service/transaction"
	"github.com/sirawong/simple-banking-api/pkg/jwt"
	"github.com/sirawong/simple-banking-api/pkg/logger"
)

// Injectors from wire.go:

// InitializeRouter wires the full handler stack for integration tests.
// db and rdb are provided externally; config is loaded from ENV_FILE env var.
func InitializeRouter(db2 *adapterdb.DB, rdb *redis.Client, log *logger.Logger) (*gin.Engine, error) {
	configConfig, err := config.ProvideConfig()
	if err != nil {
		return nil, err
	}
	manager := jwt.ProvideManager(configConfig)
	userRepository := db.ProvideUserRepository(db2)
	tokenRepository := db.ProvideTokenRepository(db2)
	service := auth.ProvideService(configConfig, manager, userRepository, tokenRepository)
	authHandler := handler.ProvideAuthHandler(service)
	accountRepository := db.ProvideAccountRepository(db2)
	repository := cache.ProvideCacheRepository(rdb)
	accountService := account.ProvideService(accountRepository, repository)
	txManager := db.ProvideTxManager(db2)
	transactionRepository := db.ProvideTransactionRepository(db2)
	transactionService := transaction.ProvideService(txManager, accountRepository, transactionRepository, repository)
	accountHandler := handler.ProvideAccountHandler(accountService, transactionService)
	transactionHandler := handler.ProvideTransactionHandler(transactionService)
	engine := handler2.ProvideRouter(manager, authHandler, accountHandler, transactionHandler, log)
	return engine, nil
}
