// Code generated by gen_wire.sh; DO NOT EDIT.
package di

import (
	"github.com/google/wire"
	pkg_jwt "github.com/sirawong/simple-banking-api/pkg/jwt"
)

var PkgSet = wire.NewSet(
	pkg_jwt.ProvideJWTManager,
)
