// Code generated by gen_wire.sh; DO NOT EDIT.
package di

import (
	"github.com/google/wire"
	internal_adapter_db "github.com/sirawong/simple-banking-api/internal/adapter/postgres"
	internal_adapter_redis "github.com/sirawong/simple-banking-api/internal/adapter/redis"
	internal_handler "github.com/sirawong/simple-banking-api/internal/handler"
	internal_handler_handler "github.com/sirawong/simple-banking-api/internal/handler/handler"
	internal_repository_postgres "github.com/sirawong/simple-banking-api/internal/repository/db"
	internal_repository_redis "github.com/sirawong/simple-banking-api/internal/repository/cache"
	internal_service_account "github.com/sirawong/simple-banking-api/internal/service/account"
	internal_service_transaction "github.com/sirawong/simple-banking-api/internal/service/transaction"
)

var InternalSet = wire.NewSet(
	internal_adapter_redis.ProvideRedisClient,
	internal_adapter_db.ProvideDB,
)

var HandlerSet = wire.NewSet(
	internal_handler_handler.ProvideTransactionHandler,
	internal_handler_handler.ProvideAccountHandler,
	internal_handler.ProvideRouter,
)

var RepositorySet = wire.NewSet(
	internal_repository_redis.ProvideCacheRepository,
	internal_repository_postgres.ProvideUserRepository,
	internal_repository_postgres.ProvideTransactionRepository,
	internal_repository_postgres.ProvideAccountRepository,
)

var ServiceSet = wire.NewSet(
	internal_service_transaction.ProvideService,
	internal_service_account.ProvideService,
)
