// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock_auth

import (
	"context"

	"github.com/sirawong/simple-banking-api/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Login provides a mock function for the type MockService
func (_mock *MockService) Login(ctx context.Context, email string, password string) (*entity.TokenPair, error) {
	ret := _mock.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *entity.TokenPair
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*entity.TokenPair, error)); ok {
		return returnFunc(ctx, email, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *entity.TokenPair); ok {
		r0 = returnFunc(ctx, email, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.TokenPair)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, email, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
func (_e *MockService_Expecter) Login(ctx interface{}, email interface{}, password interface{}) *MockService_Login_Call {
	return &MockService_Login_Call{Call: _e.mock.On("Login", ctx, email, password)}
}

func (_c *MockService_Login_Call) Run(run func(ctx context.Context, email string, password string)) *MockService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_Login_Call) Return(tokenPair *entity.TokenPair, err error) *MockService_Login_Call {
	_c.Call.Return(tokenPair, err)
	return _c
}

func (_c *MockService_Login_Call) RunAndReturn(run func(ctx context.Context, email string, password string) (*entity.TokenPair, error)) *MockService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshToken provides a mock function for the type MockService
func (_mock *MockService) RefreshToken(ctx context.Context, refreshToken string) (*entity.TokenPair, error) {
	ret := _mock.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for RefreshToken")
	}

	var r0 *entity.TokenPair
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.TokenPair, error)); ok {
		return returnFunc(ctx, refreshToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.TokenPair); ok {
		r0 = returnFunc(ctx, refreshToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.TokenPair)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, refreshToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_RefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshToken'
type MockService_RefreshToken_Call struct {
	*mock.Call
}

// RefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *MockService_Expecter) RefreshToken(ctx interface{}, refreshToken interface{}) *MockService_RefreshToken_Call {
	return &MockService_RefreshToken_Call{Call: _e.mock.On("RefreshToken", ctx, refreshToken)}
}

func (_c *MockService_RefreshToken_Call) Run(run func(ctx context.Context, refreshToken string)) *MockService_RefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_RefreshToken_Call) Return(tokenPair *entity.TokenPair, err error) *MockService_RefreshToken_Call {
	_c.Call.Return(tokenPair, err)
	return _c
}

func (_c *MockService_RefreshToken_Call) RunAndReturn(run func(ctx context.Context, refreshToken string) (*entity.TokenPair, error)) *MockService_RefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type MockService
func (_mock *MockService) Register(ctx context.Context, name string, email string, password string) (*entity.User, error) {
	ret := _mock.Called(ctx, name, email, password)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (*entity.User, error)); ok {
		return returnFunc(ctx, name, email, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) *entity.User); ok {
		r0 = returnFunc(ctx, name, email, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, name, email, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - email string
//   - password string
func (_e *MockService_Expecter) Register(ctx interface{}, name interface{}, email interface{}, password interface{}) *MockService_Register_Call {
	return &MockService_Register_Call{Call: _e.mock.On("Register", ctx, name, email, password)}
}

func (_c *MockService_Register_Call) Run(run func(ctx context.Context, name string, email string, password string)) *MockService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_Register_Call) Return(user *entity.User, err error) *MockService_Register_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockService_Register_Call) RunAndReturn(run func(ctx context.Context, name string, email string, password string) (*entity.User, error)) *MockService_Register_Call {
	_c.Call.Return(run)
	return _c
}
