// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock_db

import (
	"context"

	"github.com/sirawong/simple-banking-api/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAccountRepository creates a new instance of MockAccountRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccountRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccountRepository {
	mock := &MockAccountRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAccountRepository is an autogenerated mock type for the AccountRepository type
type MockAccountRepository struct {
	mock.Mock
}

type MockAccountRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccountRepository) EXPECT() *MockAccountRepository_Expecter {
	return &MockAccountRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockAccountRepository
func (_mock *MockAccountRepository) Create(ctx context.Context, account *entity.Account) (*entity.Account, error) {
	ret := _mock.Called(ctx, account)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entity.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Account) (*entity.Account, error)); ok {
		return returnFunc(ctx, account)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Account) *entity.Account); ok {
		r0 = returnFunc(ctx, account)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.Account) error); ok {
		r1 = returnFunc(ctx, account)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAccountRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - account *entity.Account
func (_e *MockAccountRepository_Expecter) Create(ctx interface{}, account interface{}) *MockAccountRepository_Create_Call {
	return &MockAccountRepository_Create_Call{Call: _e.mock.On("Create", ctx, account)}
}

func (_c *MockAccountRepository_Create_Call) Run(run func(ctx context.Context, account *entity.Account)) *MockAccountRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Account
		if args[1] != nil {
			arg1 = args[1].(*entity.Account)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountRepository_Create_Call) Return(account1 *entity.Account, err error) *MockAccountRepository_Create_Call {
	_c.Call.Return(account1, err)
	return _c
}

func (_c *MockAccountRepository_Create_Call) RunAndReturn(run func(ctx context.Context, account *entity.Account) (*entity.Account, error)) *MockAccountRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByAccountNumber provides a mock function for the type MockAccountRepository
func (_mock *MockAccountRepository) FindByAccountNumber(ctx context.Context, accountNumber string) (*entity.Account, error) {
	ret := _mock.Called(ctx, accountNumber)

	if len(ret) == 0 {
		panic("no return value specified for FindByAccountNumber")
	}

	var r0 *entity.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.Account, error)); ok {
		return returnFunc(ctx, accountNumber)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.Account); ok {
		r0 = returnFunc(ctx, accountNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, accountNumber)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountRepository_FindByAccountNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByAccountNumber'
type MockAccountRepository_FindByAccountNumber_Call struct {
	*mock.Call
}

// FindByAccountNumber is a helper method to define mock.On call
//   - ctx context.Context
//   - accountNumber string
func (_e *MockAccountRepository_Expecter) FindByAccountNumber(ctx interface{}, accountNumber interface{}) *MockAccountRepository_FindByAccountNumber_Call {
	return &MockAccountRepository_FindByAccountNumber_Call{Call: _e.mock.On("FindByAccountNumber", ctx, accountNumber)}
}

func (_c *MockAccountRepository_FindByAccountNumber_Call) Run(run func(ctx context.Context, accountNumber string)) *MockAccountRepository_FindByAccountNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountRepository_FindByAccountNumber_Call) Return(account *entity.Account, err error) *MockAccountRepository_FindByAccountNumber_Call {
	_c.Call.Return(account, err)
	return _c
}

func (_c *MockAccountRepository_FindByAccountNumber_Call) RunAndReturn(run func(ctx context.Context, accountNumber string) (*entity.Account, error)) *MockAccountRepository_FindByAccountNumber_Call {
	_c.Call.Return(run)
	return _c
}

// FindByAccountNumberForUpdate provides a mock function for the type MockAccountRepository
func (_mock *MockAccountRepository) FindByAccountNumberForUpdate(ctx context.Context, accountNumber string) (*entity.Account, error) {
	ret := _mock.Called(ctx, accountNumber)

	if len(ret) == 0 {
		panic("no return value specified for FindByAccountNumberForUpdate")
	}

	var r0 *entity.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.Account, error)); ok {
		return returnFunc(ctx, accountNumber)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.Account); ok {
		r0 = returnFunc(ctx, accountNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, accountNumber)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountRepository_FindByAccountNumberForUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByAccountNumberForUpdate'
type MockAccountRepository_FindByAccountNumberForUpdate_Call struct {
	*mock.Call
}

// FindByAccountNumberForUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - accountNumber string
func (_e *MockAccountRepository_Expecter) FindByAccountNumberForUpdate(ctx interface{}, accountNumber interface{}) *MockAccountRepository_FindByAccountNumberForUpdate_Call {
	return &MockAccountRepository_FindByAccountNumberForUpdate_Call{Call: _e.mock.On("FindByAccountNumberForUpdate", ctx, accountNumber)}
}

func (_c *MockAccountRepository_FindByAccountNumberForUpdate_Call) Run(run func(ctx context.Context, accountNumber string)) *MockAccountRepository_FindByAccountNumberForUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountRepository_FindByAccountNumberForUpdate_Call) Return(account *entity.Account, err error) *MockAccountRepository_FindByAccountNumberForUpdate_Call {
	_c.Call.Return(account, err)
	return _c
}

func (_c *MockAccountRepository_FindByAccountNumberForUpdate_Call) RunAndReturn(run func(ctx context.Context, accountNumber string) (*entity.Account, error)) *MockAccountRepository_FindByAccountNumberForUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUserID provides a mock function for the type MockAccountRepository
func (_mock *MockAccountRepository) FindByUserID(ctx context.Context, userID string) ([]*entity.Account, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserID")
	}

	var r0 []*entity.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*entity.Account, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*entity.Account); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountRepository_FindByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUserID'
type MockAccountRepository_FindByUserID_Call struct {
	*mock.Call
}

// FindByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockAccountRepository_Expecter) FindByUserID(ctx interface{}, userID interface{}) *MockAccountRepository_FindByUserID_Call {
	return &MockAccountRepository_FindByUserID_Call{Call: _e.mock.On("FindByUserID", ctx, userID)}
}

func (_c *MockAccountRepository_FindByUserID_Call) Run(run func(ctx context.Context, userID string)) *MockAccountRepository_FindByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountRepository_FindByUserID_Call) Return(accounts []*entity.Account, err error) *MockAccountRepository_FindByUserID_Call {
	_c.Call.Return(accounts, err)
	return _c
}

func (_c *MockAccountRepository_FindByUserID_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]*entity.Account, error)) *MockAccountRepository_FindByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockAccountRepository
func (_mock *MockAccountRepository) Update(ctx context.Context, account *entity.Account) error {
	ret := _mock.Called(ctx, account)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Account) error); ok {
		r0 = returnFunc(ctx, account)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAccountRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockAccountRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - account *entity.Account
func (_e *MockAccountRepository_Expecter) Update(ctx interface{}, account interface{}) *MockAccountRepository_Update_Call {
	return &MockAccountRepository_Update_Call{Call: _e.mock.On("Update", ctx, account)}
}

func (_c *MockAccountRepository_Update_Call) Run(run func(ctx context.Context, account *entity.Account)) *MockAccountRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Account
		if args[1] != nil {
			arg1 = args[1].(*entity.Account)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountRepository_Update_Call) Return(err error) *MockAccountRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAccountRepository_Update_Call) RunAndReturn(run func(ctx context.Context, account *entity.Account) error) *MockAccountRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
