// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock_db

import (
	"context"

	"github.com/sirawong/simple-banking-api/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTokenRepository creates a new instance of MockTokenRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenRepository {
	mock := &MockTokenRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenRepository is an autogenerated mock type for the TokenRepository type
type MockTokenRepository struct {
	mock.Mock
}

type MockTokenRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenRepository) EXPECT() *MockTokenRepository_Expecter {
	return &MockTokenRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockTokenRepository
func (_mock *MockTokenRepository) Create(ctx context.Context, token *entity.RefreshToken) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.RefreshToken) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTokenRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTokenRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - token *entity.RefreshToken
func (_e *MockTokenRepository_Expecter) Create(ctx interface{}, token interface{}) *MockTokenRepository_Create_Call {
	return &MockTokenRepository_Create_Call{Call: _e.mock.On("Create", ctx, token)}
}

func (_c *MockTokenRepository_Create_Call) Run(run func(ctx context.Context, token *entity.RefreshToken)) *MockTokenRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.RefreshToken
		if args[1] != nil {
			arg1 = args[1].(*entity.RefreshToken)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenRepository_Create_Call) Return(err error) *MockTokenRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTokenRepository_Create_Call) RunAndReturn(run func(ctx context.Context, token *entity.RefreshToken) error) *MockTokenRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByToken provides a mock function for the type MockTokenRepository
func (_mock *MockTokenRepository) DeleteByToken(ctx context.Context, token string) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTokenRepository_DeleteByToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByToken'
type MockTokenRepository_DeleteByToken_Call struct {
	*mock.Call
}

// DeleteByToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockTokenRepository_Expecter) DeleteByToken(ctx interface{}, token interface{}) *MockTokenRepository_DeleteByToken_Call {
	return &MockTokenRepository_DeleteByToken_Call{Call: _e.mock.On("DeleteByToken", ctx, token)}
}

func (_c *MockTokenRepository_DeleteByToken_Call) Run(run func(ctx context.Context, token string)) *MockTokenRepository_DeleteByToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenRepository_DeleteByToken_Call) Return(err error) *MockTokenRepository_DeleteByToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTokenRepository_DeleteByToken_Call) RunAndReturn(run func(ctx context.Context, token string) error) *MockTokenRepository_DeleteByToken_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByUserID provides a mock function for the type MockTokenRepository
func (_mock *MockTokenRepository) DeleteByUserID(ctx context.Context, userID string) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByUserID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTokenRepository_DeleteByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByUserID'
type MockTokenRepository_DeleteByUserID_Call struct {
	*mock.Call
}

// DeleteByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockTokenRepository_Expecter) DeleteByUserID(ctx interface{}, userID interface{}) *MockTokenRepository_DeleteByUserID_Call {
	return &MockTokenRepository_DeleteByUserID_Call{Call: _e.mock.On("DeleteByUserID", ctx, userID)}
}

func (_c *MockTokenRepository_DeleteByUserID_Call) Run(run func(ctx context.Context, userID string)) *MockTokenRepository_DeleteByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenRepository_DeleteByUserID_Call) Return(err error) *MockTokenRepository_DeleteByUserID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTokenRepository_DeleteByUserID_Call) RunAndReturn(run func(ctx context.Context, userID string) error) *MockTokenRepository_DeleteByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByToken provides a mock function for the type MockTokenRepository
func (_mock *MockTokenRepository) FindByToken(ctx context.Context, token string) (*entity.RefreshToken, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for FindByToken")
	}

	var r0 *entity.RefreshToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.RefreshToken, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.RefreshToken); ok {
		r0 = returnFunc(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.RefreshToken)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenRepository_FindByToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByToken'
type MockTokenRepository_FindByToken_Call struct {
	*mock.Call
}

// FindByToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockTokenRepository_Expecter) FindByToken(ctx interface{}, token interface{}) *MockTokenRepository_FindByToken_Call {
	return &MockTokenRepository_FindByToken_Call{Call: _e.mock.On("FindByToken", ctx, token)}
}

func (_c *MockTokenRepository_FindByToken_Call) Run(run func(ctx context.Context, token string)) *MockTokenRepository_FindByToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenRepository_FindByToken_Call) Return(refreshToken *entity.RefreshToken, err error) *MockTokenRepository_FindByToken_Call {
	_c.Call.Return(refreshToken, err)
	return _c
}

func (_c *MockTokenRepository_FindByToken_Call) RunAndReturn(run func(ctx context.Context, token string) (*entity.RefreshToken, error)) *MockTokenRepository_FindByToken_Call {
	_c.Call.Return(run)
	return _c
}
