// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock_db

import (
	"context"

	"github.com/sirawong/simple-banking-api/internal/domain/entity"
	"github.com/sirawong/simple-banking-api/internal/repository/db"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAccountRepository creates a new instance of MockAccountRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccountRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccountRepository {
	mock := &MockAccountRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAccountRepository is an autogenerated mock type for the AccountRepository type
type MockAccountRepository struct {
	mock.Mock
}

type MockAccountRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccountRepository) EXPECT() *MockAccountRepository_Expecter {
	return &MockAccountRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockAccountRepository
func (_mock *MockAccountRepository) Create(ctx context.Context, account *entity.Account) error {
	ret := _mock.Called(ctx, account)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Account) error); ok {
		r0 = returnFunc(ctx, account)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAccountRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAccountRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - account *entity.Account
func (_e *MockAccountRepository_Expecter) Create(ctx interface{}, account interface{}) *MockAccountRepository_Create_Call {
	return &MockAccountRepository_Create_Call{Call: _e.mock.On("Create", ctx, account)}
}

func (_c *MockAccountRepository_Create_Call) Run(run func(ctx context.Context, account *entity.Account)) *MockAccountRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Account
		if args[1] != nil {
			arg1 = args[1].(*entity.Account)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountRepository_Create_Call) Return(err error) *MockAccountRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAccountRepository_Create_Call) RunAndReturn(run func(ctx context.Context, account *entity.Account) error) *MockAccountRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockAccountRepository
func (_mock *MockAccountRepository) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAccountRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockAccountRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockAccountRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockAccountRepository_Delete_Call {
	return &MockAccountRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockAccountRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockAccountRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountRepository_Delete_Call) Return(err error) *MockAccountRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAccountRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockAccountRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockAccountRepository
func (_mock *MockAccountRepository) FindByID(ctx context.Context, id string) (*entity.Account, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.Account, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.Account); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockAccountRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockAccountRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockAccountRepository_FindByID_Call {
	return &MockAccountRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockAccountRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockAccountRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountRepository_FindByID_Call) Return(account *entity.Account, err error) *MockAccountRepository_FindByID_Call {
	_c.Call.Return(account, err)
	return _c
}

func (_c *MockAccountRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*entity.Account, error)) *MockAccountRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByIDForUpdate provides a mock function for the type MockAccountRepository
func (_mock *MockAccountRepository) FindByIDForUpdate(ctx context.Context, tx db.Tx, id string) (*entity.Account, error) {
	ret := _mock.Called(ctx, tx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByIDForUpdate")
	}

	var r0 *entity.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.Tx, string) (*entity.Account, error)); ok {
		return returnFunc(ctx, tx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.Tx, string) *entity.Account); ok {
		r0 = returnFunc(ctx, tx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.Tx, string) error); ok {
		r1 = returnFunc(ctx, tx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountRepository_FindByIDForUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByIDForUpdate'
type MockAccountRepository_FindByIDForUpdate_Call struct {
	*mock.Call
}

// FindByIDForUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - tx db.Tx
//   - id string
func (_e *MockAccountRepository_Expecter) FindByIDForUpdate(ctx interface{}, tx interface{}, id interface{}) *MockAccountRepository_FindByIDForUpdate_Call {
	return &MockAccountRepository_FindByIDForUpdate_Call{Call: _e.mock.On("FindByIDForUpdate", ctx, tx, id)}
}

func (_c *MockAccountRepository_FindByIDForUpdate_Call) Run(run func(ctx context.Context, tx db.Tx, id string)) *MockAccountRepository_FindByIDForUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.Tx
		if args[1] != nil {
			arg1 = args[1].(db.Tx)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAccountRepository_FindByIDForUpdate_Call) Return(account *entity.Account, err error) *MockAccountRepository_FindByIDForUpdate_Call {
	_c.Call.Return(account, err)
	return _c
}

func (_c *MockAccountRepository_FindByIDForUpdate_Call) RunAndReturn(run func(ctx context.Context, tx db.Tx, id string) (*entity.Account, error)) *MockAccountRepository_FindByIDForUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUserID provides a mock function for the type MockAccountRepository
func (_mock *MockAccountRepository) FindByUserID(ctx context.Context, userID string) ([]*entity.Account, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserID")
	}

	var r0 []*entity.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*entity.Account, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*entity.Account); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountRepository_FindByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUserID'
type MockAccountRepository_FindByUserID_Call struct {
	*mock.Call
}

// FindByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockAccountRepository_Expecter) FindByUserID(ctx interface{}, userID interface{}) *MockAccountRepository_FindByUserID_Call {
	return &MockAccountRepository_FindByUserID_Call{Call: _e.mock.On("FindByUserID", ctx, userID)}
}

func (_c *MockAccountRepository_FindByUserID_Call) Run(run func(ctx context.Context, userID string)) *MockAccountRepository_FindByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountRepository_FindByUserID_Call) Return(accounts []*entity.Account, err error) *MockAccountRepository_FindByUserID_Call {
	_c.Call.Return(accounts, err)
	return _c
}

func (_c *MockAccountRepository_FindByUserID_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]*entity.Account, error)) *MockAccountRepository_FindByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockAccountRepository
func (_mock *MockAccountRepository) Update(ctx context.Context, tx db.Tx, account *entity.Account) error {
	ret := _mock.Called(ctx, tx, account)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.Tx, *entity.Account) error); ok {
		r0 = returnFunc(ctx, tx, account)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAccountRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockAccountRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - tx db.Tx
//   - account *entity.Account
func (_e *MockAccountRepository_Expecter) Update(ctx interface{}, tx interface{}, account interface{}) *MockAccountRepository_Update_Call {
	return &MockAccountRepository_Update_Call{Call: _e.mock.On("Update", ctx, tx, account)}
}

func (_c *MockAccountRepository_Update_Call) Run(run func(ctx context.Context, tx db.Tx, account *entity.Account)) *MockAccountRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.Tx
		if args[1] != nil {
			arg1 = args[1].(db.Tx)
		}
		var arg2 *entity.Account
		if args[2] != nil {
			arg2 = args[2].(*entity.Account)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAccountRepository_Update_Call) Return(err error) *MockAccountRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAccountRepository_Update_Call) RunAndReturn(run func(ctx context.Context, tx db.Tx, account *entity.Account) error) *MockAccountRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
