// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock_db

import (
	"context"

	"github.com/sirawong/simple-banking-api/internal/domain/entity"
	"github.com/sirawong/simple-banking-api/internal/repository/db"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTransactionRepository creates a new instance of MockTransactionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactionRepository {
	mock := &MockTransactionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTransactionRepository is an autogenerated mock type for the TransactionRepository type
type MockTransactionRepository struct {
	mock.Mock
}

type MockTransactionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactionRepository) EXPECT() *MockTransactionRepository_Expecter {
	return &MockTransactionRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockTransactionRepository
func (_mock *MockTransactionRepository) Create(ctx context.Context, tx db.Tx, transaction *entity.Transaction) error {
	ret := _mock.Called(ctx, tx, transaction)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.Tx, *entity.Transaction) error); ok {
		r0 = returnFunc(ctx, tx, transaction)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTransactionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTransactionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - tx db.Tx
//   - transaction *entity.Transaction
func (_e *MockTransactionRepository_Expecter) Create(ctx interface{}, tx interface{}, transaction interface{}) *MockTransactionRepository_Create_Call {
	return &MockTransactionRepository_Create_Call{Call: _e.mock.On("Create", ctx, tx, transaction)}
}

func (_c *MockTransactionRepository_Create_Call) Run(run func(ctx context.Context, tx db.Tx, transaction *entity.Transaction)) *MockTransactionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.Tx
		if args[1] != nil {
			arg1 = args[1].(db.Tx)
		}
		var arg2 *entity.Transaction
		if args[2] != nil {
			arg2 = args[2].(*entity.Transaction)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTransactionRepository_Create_Call) Return(err error) *MockTransactionRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTransactionRepository_Create_Call) RunAndReturn(run func(ctx context.Context, tx db.Tx, transaction *entity.Transaction) error) *MockTransactionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByAccountID provides a mock function for the type MockTransactionRepository
func (_mock *MockTransactionRepository) FindByAccountID(ctx context.Context, accountID string, page int, limit int) ([]*entity.Transaction, int64, error) {
	ret := _mock.Called(ctx, accountID, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindByAccountID")
	}

	var r0 []*entity.Transaction
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int) ([]*entity.Transaction, int64, error)); ok {
		return returnFunc(ctx, accountID, page, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int) []*entity.Transaction); ok {
		r0 = returnFunc(ctx, accountID, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Transaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int, int) int64); ok {
		r1 = returnFunc(ctx, accountID, page, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, int, int) error); ok {
		r2 = returnFunc(ctx, accountID, page, limit)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockTransactionRepository_FindByAccountID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByAccountID'
type MockTransactionRepository_FindByAccountID_Call struct {
	*mock.Call
}

// FindByAccountID is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
//   - page int
//   - limit int
func (_e *MockTransactionRepository_Expecter) FindByAccountID(ctx interface{}, accountID interface{}, page interface{}, limit interface{}) *MockTransactionRepository_FindByAccountID_Call {
	return &MockTransactionRepository_FindByAccountID_Call{Call: _e.mock.On("FindByAccountID", ctx, accountID, page, limit)}
}

func (_c *MockTransactionRepository_FindByAccountID_Call) Run(run func(ctx context.Context, accountID string, page int, limit int)) *MockTransactionRepository_FindByAccountID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockTransactionRepository_FindByAccountID_Call) Return(transactions []*entity.Transaction, n int64, err error) *MockTransactionRepository_FindByAccountID_Call {
	_c.Call.Return(transactions, n, err)
	return _c
}

func (_c *MockTransactionRepository_FindByAccountID_Call) RunAndReturn(run func(ctx context.Context, accountID string, page int, limit int) ([]*entity.Transaction, int64, error)) *MockTransactionRepository_FindByAccountID_Call {
	_c.Call.Return(run)
	return _c
}
