// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/sirawong/simple-banking-api/internal/adapter/postgres"
	"github.com/sirawong/simple-banking-api/internal/adapter/redis"
	"github.com/sirawong/simple-banking-api/internal/config"
	handler2 "github.com/sirawong/simple-banking-api/internal/handler"
	"github.com/sirawong/simple-banking-api/internal/handler/handler"
	"github.com/sirawong/simple-banking-api/internal/repository/cache"
	"github.com/sirawong/simple-banking-api/internal/repository/db"
	"github.com/sirawong/simple-banking-api/internal/server"
	"github.com/sirawong/simple-banking-api/internal/service/account"
	authsvc "github.com/sirawong/simple-banking-api/internal/service/auth"
	"github.com/sirawong/simple-banking-api/internal/service/transaction"
	pkgjwt "github.com/sirawong/simple-banking-api/pkg/jwt"
	"github.com/sirawong/simple-banking-api/pkg/logger"
)

func InitializeApp(log *logger.Logger) (*server.App, func(), error) {
	configConfig, err := config.ProvideConfig()
	if err != nil {
		return nil, nil, err
	}
	ok := false

	gormDB, cleanupDB, err := adapterdb.ProvideDB(configConfig)
	if err != nil {
		return nil, nil, err
	}
	defer func() {
		if !ok {
			cleanupDB()
		}
	}()

	client, cleanupRedis, err := adapterredis.ProvideRedisClient(configConfig)
	if err != nil {
		return nil, nil, err
	}
	defer func() {
		if !ok {
			cleanupRedis()
		}
	}()

	jwtManager := pkgjwt.ProvideManager(configConfig)

	userRepository := db.ProvideUserRepository(gormDB)
	tokenRepository := db.ProvideTokenRepository(gormDB)
	authService := authsvc.ProvideService(configConfig, jwtManager, userRepository, tokenRepository)
	authHandler := handler.ProvideAuthHandler(authService)

	accountRepository := db.ProvideAccountRepository(gormDB)
	repository := cache.ProvideCacheRepository(client)
	accountService := account.ProvideService(accountRepository, repository)

	txManager := db.ProvideTxManager(gormDB)
	transactionRepository := db.ProvideTransactionRepository(gormDB)
	transactionService := transaction.ProvideService(txManager, accountRepository, transactionRepository, repository)

	accountHandler := handler.ProvideAccountHandler(accountService, transactionService)
	transactionHandler := handler.ProvideTransactionHandler(transactionService)
	engine := handler2.ProvideRouter(jwtManager, authHandler, accountHandler, transactionHandler, log)
	app := server.ProvideServer(configConfig, engine)

	ok = true
	return app, func() {
		cleanupRedis()
		cleanupDB()
	}, nil
}
