// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/sirawong/simple-banking-api/internal/adapter/postgres"
	"github.com/sirawong/simple-banking-api/internal/adapter/redis"
	"github.com/sirawong/simple-banking-api/internal/config"
	handler2 "github.com/sirawong/simple-banking-api/internal/handler"
	"github.com/sirawong/simple-banking-api/internal/handler/handler"
	"github.com/sirawong/simple-banking-api/internal/repository/cache"
	"github.com/sirawong/simple-banking-api/internal/repository/db"
	"github.com/sirawong/simple-banking-api/internal/server"
	"github.com/sirawong/simple-banking-api/internal/service/account"
	"github.com/sirawong/simple-banking-api/internal/service/auth"
	"github.com/sirawong/simple-banking-api/internal/service/transaction"
	"github.com/sirawong/simple-banking-api/pkg/jwt"
	"github.com/sirawong/simple-banking-api/pkg/logger"
)

// Injectors from wire.go:

func InitializeApp(log *logger.Logger) (*server.App, func(), error) {
	configConfig, err := config.ProvideConfig()
	if err != nil {
		return nil, nil, err
	}
	jwtManager := jwt.ProvideJWTManager(configConfig)
	adapterdbDB, cleanup, err := adapterdb.ProvideDB(configConfig)
	if err != nil {
		return nil, nil, err
	}
	userRepository := db.ProvideUserRepository(adapterdbDB)
	tokenRepository := db.ProvideTokenRepository(adapterdbDB)
	service := auth.ProvideService(configConfig, jwtManager, userRepository, tokenRepository)
	authHandler := handler.ProvideAuthHandler(service)
	accountRepository := db.ProvideAccountRepository(adapterdbDB)
	client, cleanup2, err := adapterredis.ProvideRedisClient(configConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	repository := cache.ProvideCacheRepository(client)
	accountService := account.ProvideService(accountRepository, repository)
	txManager := db.ProvideTxManager(adapterdbDB)
	transactionRepository := db.ProvideTransactionRepository(adapterdbDB)
	transactionService := transaction.ProvideService(txManager, accountRepository, transactionRepository, repository)
	accountHandler := handler.ProvideAccountHandler(accountService, transactionService)
	transactionHandler := handler.ProvideTransactionHandler(transactionService)
	engine := handler2.ProvideRouter(jwtManager, authHandler, accountHandler, transactionHandler, log)
	app := server.ProvideServer(configConfig, engine)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
