// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock_account

import (
	"context"

	"github.com/shopspring/decimal"
	"github.com/sirawong/simple-banking-api/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// CreateAccount provides a mock function for the type MockService
func (_mock *MockService) CreateAccount(ctx context.Context, userID string, currency string) (*entity.Account, error) {
	ret := _mock.Called(ctx, userID, currency)

	if len(ret) == 0 {
		panic("no return value specified for CreateAccount")
	}

	var r0 *entity.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*entity.Account, error)); ok {
		return returnFunc(ctx, userID, currency)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *entity.Account); ok {
		r0 = returnFunc(ctx, userID, currency)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, userID, currency)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_CreateAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAccount'
type MockService_CreateAccount_Call struct {
	*mock.Call
}

// CreateAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - currency string
func (_e *MockService_Expecter) CreateAccount(ctx interface{}, userID interface{}, currency interface{}) *MockService_CreateAccount_Call {
	return &MockService_CreateAccount_Call{Call: _e.mock.On("CreateAccount", ctx, userID, currency)}
}

func (_c *MockService_CreateAccount_Call) Run(run func(ctx context.Context, userID string, currency string)) *MockService_CreateAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_CreateAccount_Call) Return(account *entity.Account, err error) *MockService_CreateAccount_Call {
	_c.Call.Return(account, err)
	return _c
}

func (_c *MockService_CreateAccount_Call) RunAndReturn(run func(ctx context.Context, userID string, currency string) (*entity.Account, error)) *MockService_CreateAccount_Call {
	_c.Call.Return(run)
	return _c
}

// GetBalance provides a mock function for the type MockService
func (_mock *MockService) GetBalance(ctx context.Context, userID string, accountNumber string) (decimal.Decimal, error) {
	ret := _mock.Called(ctx, userID, accountNumber)

	if len(ret) == 0 {
		panic("no return value specified for GetBalance")
	}

	var r0 decimal.Decimal
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (decimal.Decimal, error)); ok {
		return returnFunc(ctx, userID, accountNumber)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) decimal.Decimal); ok {
		r0 = returnFunc(ctx, userID, accountNumber)
	} else {
		r0 = ret.Get(0).(decimal.Decimal)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, userID, accountNumber)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBalance'
type MockService_GetBalance_Call struct {
	*mock.Call
}

// GetBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - accountNumber string
func (_e *MockService_Expecter) GetBalance(ctx interface{}, userID interface{}, accountNumber interface{}) *MockService_GetBalance_Call {
	return &MockService_GetBalance_Call{Call: _e.mock.On("GetBalance", ctx, userID, accountNumber)}
}

func (_c *MockService_GetBalance_Call) Run(run func(ctx context.Context, userID string, accountNumber string)) *MockService_GetBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_GetBalance_Call) Return(decimal1 decimal.Decimal, err error) *MockService_GetBalance_Call {
	_c.Call.Return(decimal1, err)
	return _c
}

func (_c *MockService_GetBalance_Call) RunAndReturn(run func(ctx context.Context, userID string, accountNumber string) (decimal.Decimal, error)) *MockService_GetBalance_Call {
	_c.Call.Return(run)
	return _c
}

// ListAccounts provides a mock function for the type MockService
func (_mock *MockService) ListAccounts(ctx context.Context, userID string) ([]*entity.Account, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListAccounts")
	}

	var r0 []*entity.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*entity.Account, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*entity.Account); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ListAccounts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAccounts'
type MockService_ListAccounts_Call struct {
	*mock.Call
}

// ListAccounts is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockService_Expecter) ListAccounts(ctx interface{}, userID interface{}) *MockService_ListAccounts_Call {
	return &MockService_ListAccounts_Call{Call: _e.mock.On("ListAccounts", ctx, userID)}
}

func (_c *MockService_ListAccounts_Call) Run(run func(ctx context.Context, userID string)) *MockService_ListAccounts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_ListAccounts_Call) Return(accounts []*entity.Account, err error) *MockService_ListAccounts_Call {
	_c.Call.Return(accounts, err)
	return _c
}

func (_c *MockService_ListAccounts_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]*entity.Account, error)) *MockService_ListAccounts_Call {
	_c.Call.Return(run)
	return _c
}
