// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/sirawong/simple-banking-api/internal/adapter/postgres"
	"github.com/sirawong/simple-banking-api/internal/config"
	"github.com/sirawong/simple-banking-api/internal/repository/db/migrate"
	"github.com/sirawong/simple-banking-api/pkg/logger"
)

// Injectors from wire.go:

func InitializeMigrate(log *logger.Logger) (*migrate.App, func(), error) {
	configConfig, err := config.ProvideConfig()
	if err != nil {
		return nil, nil, err
	}
	db, cleanup, err := adapterdb.ProvideDB(configConfig)
	if err != nil {
		return nil, nil, err
	}
	app := migrate.ProvideMigrate(db)
	return app, func() {
		cleanup()
	}, nil
}
